use_frameworks!

target 'GomobileIPFS_Example' do
  pod 'GomobileIPFS', :path => '../'

  target 'GomobileIPFS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
